name: Second Workflow

on: [push, workflow_dispatch]

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Display text
        run: echo "Some text"

      - name: Multiline command
        run: |
          node -v
          npm -v

  second_job:
    runs-on: macos-latest
    steps:
      - name: Get Node version
        run: node -v(qweqwe)

  third_job:
    runs-on: windows-latest
    needs: [first_job, second_job]
    steps:
      - name: Get Node version
        run: node -v

  fourth_job:
    runs-on: windows-latest
    needs: [first_job]
    steps:
      - name: Get Node version
        run: node -v