name: Workflow Two

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      env:
        description: Select an required environment
        type: choice
        required: true
        options:
          - dev
          - qa
          - prod
        default: "dev"

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Display text
        run: echo "Some text"

      - name: Multiline command
        run: |
          node -v
          npm -v

  second_job:
    runs-on: macos-latest
    steps:
      - name: Get Node version
        run: node -v

  third_job:
    runs-on: windows-latest
    needs: [first_job, second_job]
    steps:
      - name: Get Node version
        run: node -v

  fourth_job:
    runs-on: windows-latest
    needs: [first_job]
    steps:
      - name: Get Node version
        run: node -v