name: workflow_four.yml
on:
  workflow_run:
    workflows: [First Workflow, Second Workflow, workflow_three]
    types:
      - completed

jobs:
  hello-comand:
    runs-on: macos-latest
    steps:
      - name: Say Hello
        run: echo "Hello!!"
