name: workflow_three.yml

on: [push, workflow_dispatch]

jobs:
  one_job:
    runs-on: ubuntu-latest
    steps:
      - name: Get list files and do checkout
        run: ls -a
      - uses: actions/checkout@v5
      - name: Get list files after checkot
        run: ls -a