name: workflow_four.yml
on:
  workflow_run:
    workflows: [First Workflow, Second Workflow, workflow_three]
    types:
      - completed

jobs:
  success-comand:
    runs-on: macos-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Success
        run: echo "Success!"
  failure-comand:
    runs-on: macos-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Failure
        run: echo "Failure"
