name: First Workflow

on: [push, workflow_dispatch]

jobs:
  run-first-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Display text
        run: echo "Some text"

      - name: Multiline command
        run: |
          node -v
          npm -v
