name: workflow_three

on: [push, workflow_dispatch]

jobs:
  one_job:
    runs-on: ubuntu-latest
    steps:
      - name: Get list files and do checkout
        run: |
          git init
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git fetch origin
          git checkout main
#        run: ls -a
#      - uses: actions/checkout@v5
      - name: Get list files after checkot
        run: ls -a