name: First Workflow

on: [push]

jobs:
  run-first-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Display text
        run: echo "Some text"

      - name: Check Python version
        run: python â€“version
